# Basic
title: 伪·红魔馆
subtitle: 个人站
welcome_message: 欢迎来到这个假的红魔馆
description: 假红魔馆的伪·大图书馆
creator:

url: "http://ftmc.me"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: stlate

# The blog button should not be removed.
blog_button:
    title: 博客主页
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: vno-jekyll
    # duoshuo:

# Social
social:
    # weibo: onevcat
    github: FishMagic
    # twitter: onevcat
    # gplus: 107108267983477358170
    mail: fish_magic@ftmc.me

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
